#!/usr/bin/env python3
"""Regenerate the derived parts of wiki/index.md from the database.

TWO THINGS DRIFT HERE, one level apart.

The COVERAGE TABLE used to be hand-maintained and had drifted badly — it claimed
1,325 polities in the CSV when there were 740, 467 pages when every polity had one,
and counted a `status: contested` that no longer exists anywhere. Numbers that are
cheap to compute should not be typed by hand.

The CURATED PER-CONTINENT NOTES then turned out to have the same problem one level
down. Each entry reads

    - [Serbia](polities/srb-2008-2025.md) — `SRB-2008-2025`, draft.

and that trailing word is a copy of the page's `status`, typed by hand. Measured
2026-08-05: 52 of 192 such lines contradicted the database — 38 rows were `reviewed`
and still said `draft`, and, worse, 2 RETIRED and 8 SUPERSEDED rows were presented as
`draft`, so the index told a reader that a dead polity was live. Seven links pointed
at pages that do not exist at all, left behind when a polity was split into finer
periods (`CAN-1866-1948` became `CAN-1886-1948`, `TWN-1896-2025` became two rows).

So this script now owns the status token as well. It rewrites only that one derived
word; the surrounding prose is curated and is left exactly as written.

Usage:
  python3 scripts/update_wiki_index.py [--check]

`--check` exits 1 if either the table or any status token is out of date, or if any
polity link is dead, without writing. Wired into CI.
"""
import argparse, glob, os, re, sys
import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(REPO, "wiki/index.md")
CSV = os.path.join(REPO, "data/final/polities_database.csv")
BEGIN = "<!-- BEGIN AUTOGENERATED COVERAGE -->"
END = "<!-- END AUTOGENERATED COVERAGE -->"

ap = argparse.ArgumentParser()
ap.add_argument("--check", action="store_true", help="verify without writing; exit 1 if stale")
A = ap.parse_args()

pol = pd.read_csv(CSV)
pages = [f for f in glob.glob(os.path.join(REPO, "wiki/polities/*.md"))
         if not os.path.basename(f).startswith("_")]
sources = [f for f in glob.glob(os.path.join(REPO, "wiki/sources/*.md"))
           if not os.path.basename(f).startswith("_")]
page_text = {f: open(f, encoding="utf-8").read() for f in pages}

citing_biger = sum(1 for t in page_text.values() if "sources/biger-1995.md" in t)
open_questions = sum(len(re.findall(r"(?m)^### oq-", t)) for t in page_text.values())
uncited = sum(1 for t in page_text.values() if not re.search(r"\]\(\.\./sources/", t))

def n(status): return int((pol.wiki_status == status).sum())

rows = [
    ("Polities in the database", f"{len(pol)}"),
    ("Polity pages", f"{len(pages)}" + ("" if len(pages) == len(pol) else f" ⚠ differs from database")),
    ("Sources ingested", f"{len(sources)}"),
    ("`status: draft`", f"{n('draft')}"),
    ("`status: reviewed`", f"{n('reviewed')}"),
    ("`status: superseded` / `retired`", f"{n('superseded')} / {n('retired')}"),
    ("Pages with no source citation", f"{uncited}"),
    ("Pages citing biger-1995", f"{citing_biger}"),
    ("Open questions (`### oq-`)", f"{open_questions}"),
]
by_cont = pol.continent.value_counts()
cont = " · ".join(f"{k} {v}" for k, v in by_cont.items())

table = [BEGIN,
         "",
         "| Metric | Value |",
         "|---|---|"]
table += [f"| {k} | {v} |" for k, v in rows]
table += ["",
          f"**By continent:** {cont}",
          "",
          "Regenerate with `python3 scripts/update_wiki_index.py`. The authoritative",
          "catalog is `data/final/polities_database.csv`; the per-continent notes below",
          "are a **curated selection**, not a complete listing.",
          "",
          END]
block = "\n".join(table)

text = open(INDEX, encoding="utf-8").read()
if BEGIN in text and END in text:
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.S)
else:
    # first run: replace the old hand-written Coverage section wholesale
    m = re.search(r"(?m)^## Coverage$.*?(?=^## )", text, flags=re.S)
    if not m:
        print("could not find a '## Coverage' section to replace", file=sys.stderr)
        sys.exit(2)
    new = text[:m.start()] + "## Coverage\n\n" + block + "\n\n" + text[m.end():]

# ---------- STATUS TOKENS IN THE CURATED NOTES ----------
# Each entry carries a hand-typed copy of the page's status. Rewrite just that word.
# The status may be followed by "." or by ", N open questions." — both forms exist, so
# the pattern stops at a word boundary and leaves whatever follows untouched.
ENTRY = re.compile(
    r"(- \[[^\]]*\]\(polities/([a-z0-9][a-z0-9\-]*)\.md\) — `([A-Z0-9][A-Z0-9\-]*)`, )([a-z]+)\b"
)
db_status = dict(zip(pol.polity_code, pol.wiki_status))
page_slugs = {os.path.basename(f)[:-3] for f in pages}

drifted, dead_links, unknown_codes, slug_mismatch = [], [], [], []

def fix_entry(m):
    head, slug, code, declared = m.group(1), m.group(2), m.group(3), m.group(4)
    if slug not in page_slugs:
        dead_links.append((slug, code))
        return m.group(0)
    if code.lower() != slug:
        slug_mismatch.append((slug, code))
    actual = db_status.get(code)
    if actual is None:
        unknown_codes.append((slug, code))
        return m.group(0)
    if actual != declared:
        drifted.append((code, declared, actual))
        return head + actual
    return m.group(0)

new = ENTRY.sub(fix_entry, new)

# Links anywhere in the index, not only in status-bearing entries.
for slug in sorted(set(re.findall(r"\(polities/([a-z0-9][a-z0-9\-]*)\.md\)", new))):
    if slug not in page_slugs and slug not in {s for s, _ in dead_links}:
        dead_links.append((slug, "(no status token)"))

problems = []
for code, declared, actual in drifted:
    problems.append(f"{code}: index says {declared!r}, database says {actual!r}")
for slug, code in dead_links:
    problems.append(f"{slug}.md does not exist (index links to it as {code})")
for slug, code in unknown_codes:
    problems.append(f"{code} is not in the database (index links {slug}.md)")
for slug, code in slug_mismatch:
    problems.append(f"{code} does not match its own link {slug}.md")

if A.check:
    if new == text and not problems:
        print(f"--check: PASS — wiki/index.md is current ({len(pol)} polities, "
              f"{len(db_status)} codes, {len(page_slugs)} pages)")
        sys.exit(0)
    print("--check: FAIL — wiki/index.md is out of date\n")
    for p in problems:
        print(f"  {p}")
    if new != text and not problems:
        print("  the coverage table is stale")
    print("\n  Run python3 scripts/update_wiki_index.py. Status drift is rewritten "
          "automatically; a dead link or an unknown code needs a human, because the "
          "right target is a judgement — a split polity has more than one successor.")
    sys.exit(1)

open(INDEX, "w", encoding="utf-8").write(new)
print(f"wiki/index.md regenerated ({len(pol)} polities, {len(pages)} pages, "
      f"{len(sources)} sources, {open_questions} open questions)")
print(f"  status tokens rewritten: {len(drifted)}")
for code, declared, actual in drifted[:8]:
    print(f"    {code}: {declared} -> {actual}")
if len(drifted) > 8:
    print(f"    ... and {len(drifted) - 8} more")
if dead_links or unknown_codes or slug_mismatch:
    print(f"  NOT fixed automatically, {len(dead_links) + len(unknown_codes) + len(slug_mismatch)} "
          f"need a human:")
    for p in problems[len(drifted):]:
        print(f"    {p}")
    sys.exit(1)
