#!/usr/bin/env python3
"""Regenerate the coverage table in wiki/index.md from the database.

The table used to be hand-maintained and had drifted badly — it claimed 1,325
polities in the CSV when there were 740, 467 pages when every polity had one, and
counted a `status: contested` that no longer exists anywhere. Numbers that are
cheap to compute should not be typed by hand.

Only the block between the AUTOGENERATED markers is touched; the curated
per-continent notes below it are left alone.

Usage:
  python3 scripts/update_wiki_index.py [--check]

`--check` exits 1 if the table is out of date without writing, for CI.
"""
import argparse, glob, os, re, sys
import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(REPO, "wiki/index.md")
CSV = os.path.join(REPO, "data/final/polities_database.csv")
BEGIN = "<!-- BEGIN AUTOGENERATED COVERAGE -->"
END = "<!-- END AUTOGENERATED COVERAGE -->"

ap = argparse.ArgumentParser()
ap.add_argument("--check", action="store_true", help="verify without writing; exit 1 if stale")
A = ap.parse_args()

pol = pd.read_csv(CSV)
pages = [f for f in glob.glob(os.path.join(REPO, "wiki/polities/*.md"))
         if not os.path.basename(f).startswith("_")]
sources = [f for f in glob.glob(os.path.join(REPO, "wiki/sources/*.md"))
           if not os.path.basename(f).startswith("_")]
page_text = {f: open(f, encoding="utf-8").read() for f in pages}

citing_biger = sum(1 for t in page_text.values() if "sources/biger-1995.md" in t)
open_questions = sum(len(re.findall(r"(?m)^### oq-", t)) for t in page_text.values())
uncited = sum(1 for t in page_text.values() if not re.search(r"\]\(\.\./sources/", t))

def n(status): return int((pol.wiki_status == status).sum())

rows = [
    ("Polities in the database", f"{len(pol)}"),
    ("Polity pages", f"{len(pages)}" + ("" if len(pages) == len(pol) else f" ⚠ differs from database")),
    ("Sources ingested", f"{len(sources)}"),
    ("`status: draft`", f"{n('draft')}"),
    ("`status: reviewed`", f"{n('reviewed')}"),
    ("`status: superseded` / `retired`", f"{n('superseded')} / {n('retired')}"),
    ("Pages with no source citation", f"{uncited}"),
    ("Pages citing biger-1995", f"{citing_biger}"),
    ("Open questions (`### oq-`)", f"{open_questions}"),
]
by_cont = pol.continent.value_counts()
cont = " · ".join(f"{k} {v}" for k, v in by_cont.items())

table = [BEGIN,
         "",
         "| Metric | Value |",
         "|---|---|"]
table += [f"| {k} | {v} |" for k, v in rows]
table += ["",
          f"**By continent:** {cont}",
          "",
          "Regenerate with `python3 scripts/update_wiki_index.py`. The authoritative",
          "catalog is `data/final/polities_database.csv`; the per-continent notes below",
          "are a **curated selection**, not a complete listing.",
          "",
          END]
block = "\n".join(table)

text = open(INDEX, encoding="utf-8").read()
if BEGIN in text and END in text:
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.S)
else:
    # first run: replace the old hand-written Coverage section wholesale
    m = re.search(r"(?m)^## Coverage$.*?(?=^## )", text, flags=re.S)
    if not m:
        print("could not find a '## Coverage' section to replace", file=sys.stderr)
        sys.exit(2)
    new = text[:m.start()] + "## Coverage\n\n" + block + "\n\n" + text[m.end():]

if A.check:
    if new == text:
        print(f"--check: PASS — wiki/index.md coverage table is current ({len(pol)} polities)")
        sys.exit(0)
    print("--check: FAIL — wiki/index.md coverage table is stale; run "
          "python3 scripts/update_wiki_index.py")
    sys.exit(1)

open(INDEX, "w", encoding="utf-8").write(new)
print(f"wiki/index.md coverage table regenerated ({len(pol)} polities, {len(pages)} pages, "
      f"{len(sources)} sources, {open_questions} open questions)")
